ruby/rails_projects/sample_app_test_gem/config/routes.rb
SampleApp::Application.routes.draw do

  resources :users

  match '/signup',  :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/nonsportif', :to => 'users#nonsportif'
  match '/statistiques', :to => 'pages#statistiques'
  
  root :to => 'pages#home'

end

ruby/rails_projects/sample_app_test_gem/app/models/user.rb
# encoding: UTF-8
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  nom                    :string(255)
#  email                  :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  dateNaissance          :date
#  poidsActuel            :integer
#  poidsIdeal             :integer
#  estSportif             :boolean
#  souhaitePratiquerSport :boolean
#  taille                 :integer
#
require 'prawn'
require 'imc'

class User < ActiveRecord::Base


  has_attached_file :cvpdf ,:styles => {:thumb => ["600x600", :png]}


  attr_accessible :email, :nom, :dateNaissance, :poidsActuel, :poidsIdeal, :estSportif, :souhaitePratiquerSport, :taille, :cvpdf
  # attr_accessor :dateNaissance, :poidsActuel, :poidsIdeal, :estSportif, :souhaitePratiquerSport
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :nom,  :presence => true, :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  validates_numericality_of :poidsActuel, :greater_than => Proc.new {|user| user.poidsIdeal }

 	def age
 		if self.dateNaissance > Date.today
 			"Visiteur du futur"
 		else	
	    now = Time.now.utc.to_date
	    now.year - self.dateNaissance.year - ((now.month > self.dateNaissance.month || (now.month == self.dateNaissance.month && now.day >= self.dateNaissance.day)) ? 0 : 1)
  	end
  end

  def imc
  	imc_value = Imc.new(self.taille, self.poidsActuel)
  	imc_value.calcul_imc
	end
end

ruby/rails_projects/sample_app_test_gem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ruby/rails_projects/sample_app_test_gem/app/controllers/pages_controller.rb
# encoding: UTF-8
require 'user_statistics'
class PagesController < ApplicationController
 def home
    @titre = "Accueil"
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre = "À Propos"
  end

  def help
    @titre = "Aide"
  end

  def statistiques
    @titre = "Statistiques"
    @users = User.all
    @user_statistics = UserStatistics.new(@users)
  end
end

ruby/rails_projects/sample_app_test_gem/app/controllers/users_controller.rb
# encoding: UTF-8
require 'user_statistics'

class UsersController < ApplicationController

  def new
    @user = User.new
    @titre = "Inscription"
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @titre = "Liste des utilisateurs"
    @users = User.all
    
    respond_to do |format|
      format.html
      format.pdf
    end
  end

	def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Inscription de l'utilisateur réussie!"
      redirect_to @user
    else
      @titre = "Inscription"
      render 'new'
    end
  end

  def nonsportif
    @users = User.where(estSportif: false, souhaitePratiquerSport: true)
    @titre = "Liste des utilisateurs non sportif"
    render 'index'
  end

end

ruby/rails_projects/sample_app_test_gem/app/helpers/application_helper.rb
module ApplicationHelper
	# Retourner un titre basé sur la page.
  def titre
    base_titre = "Simple App du Tutoriel Ruby on Rails"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end
end

ruby/rails_projects/sample_app_test_gem/app/helpers/pages_helper.rb
module PagesHelper
end

ruby/rails_projects/sample_app_test_gem/app/helpers/users_helper.rb
module UsersHelper

end

ruby/rails_projects/sample_app_test_gem/app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

ruby/rails_projects/sample_app_test_gem/app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("logo.png", :alt => "Application exemple", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Accueil", root_path %></li>
      <li><%= link_to "Utilisateurs", users_path %></li>
      <li><%= link_to "Non Sportifs", nonsportif_path %></li>
      <li><%= link_to "Statistiques", statistiques_path %></li>
      <li><%= link_to "Aide", help_path %></li>
      <li><%= link_to "S'enregistrer", signup_path %></li>
    </ul>
  </nav>
</header>

ruby/rails_projects/sample_app_test_gem/app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

ruby/rails_projects/sample_app_test_gem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<html>
  <head>
    <title><%= titre %></title>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag "application" %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
         <!-- flash messages -->
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

ruby/rails_projects/sample_app_test_gem/app/views/pages/about.html.erb
<h1>À Propos de nous</h1>
<p>
  <a href="http://railstutorial.org/">Le Tutoriel Ruby on Rails</a>
  est un projet de livre et de screencasts pour apprendre le développement web
  avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. Ceci
  est l'Application Exemple du tutoriel.
</p>

ruby/rails_projects/sample_app_test_gem/app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
	Contact Ruby on Rails Tutorial à propos de l'Application Exemple à
	<a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

ruby/rails_projects/sample_app_test_gem/app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails Tutorial sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette application exemple, consultez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

ruby/rails_projects/sample_app_test_gem/app/views/pages/home.html.erb
<h1>Application contrôle continu</h1>

<p>
  Page d'accueil pour l'application demandé en contrôle continu en Master 1 Informatique semestre 2 <br/>
  <a href="http://forge.info.univ-angers.fr/~gh/Scripts/cc2013.php">Sujet</a>.
</p>

<%= link_to "Enregistrer un utilisateur", signup_path, :class => "signup_button round" %>

ruby/rails_projects/sample_app_test_gem/app/views/pages/statistiques.html.erb
<h1>Statistiques</h1>
<%= render partial: "shared/graphics_box_plot_poids", locals: {user_statistics: @user_statistics} %>
<%= render partial: "shared/graphics_repartition_imc", locals: {user_statistics: @user_statistics} %>
<%= render partial: "shared/graphics_poids_ac_ic", locals: {user_statistics: @user_statistics} %> 

ruby/rails_projects/sample_app_test_gem/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "erreur") %> 
        ont empêché d'enregistrer votre inscription</h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

ruby/rails_projects/sample_app_test_gem/app/views/shared/_graphics_box_plot_poids.html.erb
<script src="http://code.highcharts.com/highcharts-more.js"></script>
<div id="graphique_box_plot_poids" style="height: 400px; margin: auto; min-width: 310px; max-width: 600px"></div>

<script type="text/javascript">
$(function () {
    $('#graphique_box_plot_poids').highcharts({

	    chart: {
	        type: 'boxplot'
	    },
	    
	    title: {
	        text: 'Répartition des poids actuels et idéals'
	    },
	    
	    legend: {
	        enabled: false
	    },
	
	    xAxis: {
	        categories: ['Poids Actuels', 'Poids Ideals']
	    },
	    
	    yAxis: {
	        title: {
	            text: 'Kilogrammes'
	        },
	        plotLines: [{
	            value: 932,
	            color: 'red',
	            width: 1,
	            label: {
	                text: 'Theoretical mean: 932',
	                align: 'center',
	                style: {
	                    color: 'gray'
	                }
	            }
	        }]  
	    },
	
	    series: [{
	        name: 'Observations',
	        data: [
	            <%=@user_statistics.poids_ac_plot.as_json%>,
	            <%=@user_statistics.poids_id_plot.as_json%>
	        ],
	        tooltip: {
	            headerFormat: '<em>{point.key}</em><br/>'
	        }
	    }]
	
	});
});
</script>

ruby/rails_projects/sample_app_test_gem/app/views/shared/_graphics_poids_ac_ic.html.erb
<div id="graphique_repartition_poids_ac_ic" style="width:100%; height:400px;"></div>

<script type="text/javascript"> 
    $(function () { 
        $('#graphique_repartition_poids_ac_ic').highcharts({
            chart: {
                type: 'line'
            },
            title: {
                text: 'Courbe des Poids Actuels et Idéaux des utilisateurs'
            },
            yAxis: {
                title: {
                    text: 'Poigs en kg'
                }
            },
            series: [{
                name: 'Poids Actuels',
                data: <%=@user_statistics.poids_ac%>
            }, {
                name: 'Poids Idéaux',
                data: <%=@user_statistics.poids_id%>
            }]
        });
    });
</script>

ruby/rails_projects/sample_app_test_gem/app/views/shared/_graphics_repartition_imc.html.erb
<div id="graphique_repartition_imc" style="width:100%; height:400px;"></div>

<script type="text/javascript"> 

    $(function () {
        $('#graphique_repartition_imc').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Répartition des imc utilisateurs'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            series: [{
                type: 'pie',
                name: 'Browser share',
                data: <%= raw @user_statistics.datas.as_json %>
            }]
        });
    });
</script>

ruby/rails_projects/sample_app_test_gem/app/views/users/index.html.erb
<h1>List des utilisateurs</h1>
<p class="export">Télécharger la liste des utilisateurs en pdf <%= link_to image_tag("pdf_export.png", size: "25x25"), "/users.pdf"%></p>

<table>                         
  <tr>                          
    <th>Nom</th>
    <th>Email</th>
    <th>Date de Naissance</th>
    <th>Age</th>
    <th>Taille</th>
    <th>PoidsA</th>
    <th>PoidsI</th>
    <th>IMC</th>
    <th>Sportif</th>
    <th>Souhaite Pratiquer</th>
    <th>CV</th>
  </tr>
	<% @users.each do |user| %>
	  <tr>
			<td><%= link_to user.nom, user %></td>
			<td><%= user.email%></td>
			<td><%= user.dateNaissance%></td>
			<td><%= user.age %></td>
			<td><%= user.taille %></td>
			<td><%= user.poidsActuel%></td>
			<td><%= user.poidsIdeal%></td>
			<td><%= user.imc %></td>
			<td><%= user.estSportif ? "oui" : "non" %></td>
			<td><%= user.souhaitePratiquerSport  ? "oui" : "non" %></td>
			<td><%= link_to "Download", user.cvpdf.url(:original, false) if user.cvpdf.size %></td>
	  </tr>
	<% end %>
</table>

ruby/rails_projects/sample_app_test_gem/app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label "Date de Naissance" %><br />
    <%= f.date_select :dateNaissance,  start_year: 1901 %>
  </div>
  <div class="field">
    <%= f.label "Poids Actuel" %><br />
    <%= f.text_field :poidsActuel %>
  </div>
  <div class="field">
    <%= f.label "Poids Ideal" %><br />
    <%= f.text_field :poidsIdeal %>
  </div>
  <div class="field">
    <%= f.label :taille %><br />
    <%= f.text_field :taille %>
  </div>
  <div class="field">
    <%= f.label "Pratiquez vous un sport ?" %>
    <%= f.label "Oui" %><%= f.radio_button :estSportif, 1%>
    <%= f.label "Non" %><%= f.radio_button :estSportif, 0, :checked => true %>
  </div>
  <div class="field" id="souhaite_sport">
    <%= f.label "Souhaitez faire du sport ?" %>
    <%= f.label "Oui" %><%= f.radio_button :souhaitePratiquerSport, 1 %>
    <%= f.label "Non" %><%= f.radio_button :souhaitePratiquerSport, 0, :checked => true %>
  </div>
  <div class="field">
    <%= f.label "Vous pouvez déposer votre cv ici : " %>
    <%= f.file_field :cvpdf %>
  </div>
  <div class="actions">
    <%= f.submit "Inscription" %>
  </div>
<% end %>

<script type="text/javascript">
  jQuery("#user_estSportif_0").click(function() 
      {
              jQuery("#souhaite_sport").show();
      });

  jQuery("#user_estSportif_1").click(function() 
      {
              jQuery("#souhaite_sport").hide();
      });
</script>

ruby/rails_projects/sample_app_test_gem/app/views/users/show.html.erb
<div class="fiche">
  <div id= "fiche_infos" class="left-sidebar">
    <div>
      <p><%= @user.nom%></p>
      <p><%=@user.email%></p>
    </div>
  
    <div>
      <p>Age : <%= @user.age %> ans</p>
      <p>Taille : <%= @user.taille %> cm</p>
      <p>Poids Actuel : <%= @user.poidsActuel%> kg</p>
      <p>Poids Ideal : <%= @user.poidsIdeal%> kg</p>
      <p>Imc : <%= @user.imc %></p>      
    </div>
  </div>

  <div id="fiche_sport" class="right-sidebar">
    <p>Sportif : <%= @user.estSportif ? "Oui" : "Non" %></p>
    <p>Souhaite Pratiquer un sport : <%= @user.souhaitePratiquerSport ? "Oui" : "Non"%></p>
  </div>

  <% if @user.cvpdf.size %>
    <div id= "fiche_thumb" class="right-sidebar thumb">
      <p>Cv : <%= link_to image_tag("save_pdf.ico", size: "25x25"), @user.cvpdf.url(:original, false) %></p>
      <%= image_tag @user.cvpdf.url(:thumb)%>
    </div>
  <% end %>
</div>